export function getAdminScript(apiBase: string, loginPath: string, logoutPath: string): string {
  return `const API='${apiBase}';
let turnstileSiteKey=null;
let turnstileWidgetId=null;
async function loadTurnstileScript(){if(window.turnstile)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';s.async=true;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function initAdminTurnstile(){try{const r=await fetch('/api/config');const d=await r.json();if(!d.success||!d.config||!d.config.turnstile||!d.config.turnstile.enabled||!d.config.turnstile.siteKey)return;turnstileSiteKey=d.config.turnstile.siteKey;await loadTurnstileScript();const el=document.getElementById('turnstileLogin');if(el&&window.turnstile){turnstileWidgetId=window.turnstile.render(el,{sitekey:turnstileSiteKey,theme:'dark'})}}catch(e){}}
function getTurnstileToken(){if(!turnstileSiteKey||!window.turnstile||turnstileWidgetId==null)return '';return window.turnstile.getResponse(turnstileWidgetId)||''}
function resetTurnstile(){if(window.turnstile&&turnstileWidgetId!=null)window.turnstile.reset(turnstileWidgetId)}
async function api(path,opts={}){const r=await fetch(API+path,{...opts,credentials:'include',headers:{'Content-Type':'application/json',...(opts.headers||{})}});if(r.status===401){showLogin();throw new Error('未授权')}return r.json()}
function showLogin(){document.getElementById('loginView').style.display='flex';document.getElementById('appView').style.display='none'}
function showApp(){document.getElementById('loginView').style.display='none';document.getElementById('appView').style.display='block'}
async function doLogin(){const pw=document.getElementById('passwordInput').value;const err=document.getElementById('loginError');err.style.display='none';const body={password:pw};if(turnstileSiteKey){const ts=getTurnstileToken();if(!ts){err.textContent='请先完成人机验证';err.style.display='block';return}body.turnstileToken=ts}try{const r=await fetch('${loginPath}',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)});const d=await r.json();if(!d.success){resetTurnstile();err.textContent=d.error||'登录失败';err.style.display='block';return}showApp();loadAll()}catch(e){resetTurnstile();err.textContent='网络错误';err.style.display='block'}}
async function doLogout(){await fetch('${logoutPath}',{method:'POST',credentials:'include'});showLogin()}
function switchTab(name){document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===name));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id==='panel-'+name));if(name==='users'){loadUsers();loadRegistration()}if(name==='domains')loadDomains();if(name==='announcements')loadAnnouncements();if(name==='rules'){window._templateFilter=window._templateFilter||'pending';loadRuleTemplates();loadRules()}if(name==='ratelimit')loadRateLimitStats();if(name==='settings')loadMaintenance();if(name==='audit')loadAuditLogs(1)}
function setTemplateFilter(f){window._templateFilter=f;document.querySelectorAll('[data-tfilter]').forEach(b=>b.classList.toggle('active',b.dataset.tfilter===f));loadRuleTemplates()}
async function loadRuleTemplates(){const status=window._templateFilter||'pending';const d=await api('/extract-rule-templates?status='+status);const b=document.getElementById('ruleTemplatesBody');const list=d.templates||[];if(!list.length){b.innerHTML='<tr><td colspan="8" class="empty">暂无模板</td></tr>';return}b.innerHTML=list.map(t=>{const st=t.status==='pending'?'badge-warn':t.status==='approved'?'badge-ok':'badge-off';const stLabel=t.status==='pending'?'待审核':t.status==='approved'?'已通过':'已拒绝';let actions='';if(t.status==='pending'){actions='<button class="btn btn-sm" data-action="approveTemplate" data-id="'+t.id+'">通过</button> <button class="btn btn-sm" data-action="rejectTemplate" data-id="'+t.id+'">拒绝</button> '}actions+='<button class="btn btn-danger btn-sm" data-action="deleteTemplate" data-id="'+t.id+'">删除</button>';return '<tr><td>'+t.id+'</td><td>'+esc(t.title)+'</td><td>'+esc(t.domain)+'</td><td><code>'+esc(t.regex)+'</code></td><td>'+esc(t.authorUsername||('#'+t.authorUserId))+'</td><td><span class="badge '+st+'">'+stLabel+'</span></td><td>'+t.installCount+'</td><td>'+actions+'</td></tr>'}).join('');window._ruleTemplates=list}
async function approveTemplate(id){await api('/extract-rule-templates/'+id+'/approve',{method:'POST'});loadRuleTemplates()}
async function rejectTemplate(id){const reason=prompt('拒绝原因（可选）');if(reason===null)return;await api('/extract-rule-templates/'+id+'/reject',{method:'POST',body:JSON.stringify({reason:reason||''})});loadRuleTemplates()}
async function deleteTemplate(id){if(!confirm('确定删除此模板？'))return;await api('/extract-rule-templates/'+id,{method:'DELETE'});loadRuleTemplates()}
function hideModal(id){document.getElementById(id).classList.remove('show')}
function showModal(id){document.getElementById(id).classList.add('show')}
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function fmtTime(ts){if(!ts)return'-';const d=new Date(ts>1e12?ts:ts*1000);return d.toLocaleString('zh-CN')}
async function loadAll(){await Promise.all([loadHealthStatus(),loadStats(),loadBrevoStats()])}
function statusLabel(s){if(s==='ok')return'正常';if(s==='degraded')return'降级';return'故障'}
function statusBadgeClass(s){if(s==='ok')return'badge-ok';if(s==='degraded')return'badge-warn';return'badge-off'}
function checkDisplay(check){if(check&&check.configured===false)return{icon:'',text:'未配置',cls:'badge-builtin'};if(check&&check.ok)return{icon:'✅',text:'正常',cls:'badge-ok'};return{icon:'❌',text:'异常',cls:'badge-off'}}
async function loadHealthStatus(){const hint=document.getElementById('healthHint');hint.style.color='#64748b';try{const r=await fetch('/api/public/status',{credentials:'include'});const d=await r.json();if(!r.ok||!d.success){throw new Error(d.message||d.error||'请求失败')}const mb=document.getElementById('maintBanner');if(d.maintenance&&d.maintenance.enabled){mb.style.display='block';mb.textContent='⚠ 维护模式已启用：'+(d.maintenance.displayMessage||d.maintenance.message||'系统维护中，部分功能暂不可用')}else{mb.style.display='none'}const checks=d.checks||{};const overallCls=statusBadgeClass(d.status);const rows=[['D1 数据库',checks.d1],['R2 存储',checks.r2],['Brevo API',checks.brevo]];document.getElementById('healthGrid').innerHTML='<div class="stat"><div class="label">整体状态</div><div class="value" style="font-size:1.25rem"><span class="badge '+overallCls+'">'+statusLabel(d.status)+'</span></div></div>'+rows.map(([lbl,chk])=>{const disp=checkDisplay(chk);return'<div class="stat"><div class="label">'+lbl+'</div><div class="value" style="font-size:1.25rem"><span class="badge '+disp.cls+'">'+(disp.icon?disp.icon+' ':'')+disp.text+'</span></div></div>'}).join('');const hints=[];if(checks.d1&&!checks.d1.ok&&checks.d1.message)hints.push('D1: '+checks.d1.message);if(checks.r2&&!checks.r2.ok&&checks.r2.message)hints.push('R2: '+checks.r2.message);if(checks.brevo&&checks.brevo.configured&&!checks.brevo.ok&&checks.brevo.message)hints.push('Brevo: '+checks.brevo.message);hint.textContent=hints.length?hints.join(' · '):'上次刷新：'+new Date().toLocaleString('zh-CN')}catch(e){hint.textContent='无法获取健康状态：'+(e.message||'网络错误');hint.style.color='#f87171'}}
async function loadStats(){const d=await api('/stats');const s=d.stats;document.getElementById('statsGrid').innerHTML=[
  ['用户总数',s.totalUsers],['启用用户',s.activeUsers],['有效邮箱',s.activeMailboxes],['邮箱总数',s.totalMailboxes],
  ['今日收信',s.receivedToday],['今日发信',s.sentToday],['今日活跃用户',s.activeUsersToday],['有效用户 Token',s.activeUserTokens]
].map(([l,v])=>'<div class="stat"><div class="label">'+l+'</div><div class="value">'+v+'</div></div>').join('')}
async function loadBrevoStats(){const d=await api('/brevo-stats');const s=d.stats;const l=s.local;document.getElementById('brevoStatsGrid').innerHTML=[
  ['今日发信',l.sentToday],['今日失败',l.failedToday],['累计失败',l.failedTotal],['用户日配额合计',l.userQuotaSum]
].map(([lbl,v])=>'<div class="stat"><div class="label">'+lbl+'</div><div class="value">'+v+'</div></div>').join('');
const hint=document.getElementById('brevoHint');
if(s.brevoAvailable&&s.brevo){hint.textContent='Brevo 账户: '+s.brevo.email+' · 套餐: '+s.brevo.planType+' · Credits: '+JSON.stringify(s.brevo.credits);hint.style.color='#86efac'}else{hint.textContent='Brevo API: '+esc(s.brevoError||'不可用')+'（仅显示本地统计）';hint.style.color='#94a3b8'}}
function statusCodeBadge(code){if(code>=200&&code<300)return'badge-ok';if(code>=400&&code<500)return'badge-warn';if(code>=500)return'badge-off';return'badge-builtin'}
function fmtChartDate(d){const p=d.split('-');return parseInt(p[1],10)+'/'+parseInt(p[2],10)}
function drawRequestTrendChart(trend){const host=document.getElementById('requestTrendChart');const legend=document.getElementById('requestTrendLegend');if(!trend||!trend.dates||!trend.dates.length){host.innerHTML='<div class="chart-empty">暂无趋势数据</div>';legend.innerHTML='';return}const dates=trend.dates;const series=trend.series||[];const W=800;const H=280;const pad={t:16,r:16,b:36,l:48};const plotW=W-pad.l-pad.r;const plotH=H-pad.t-pad.b;const maxY=Math.max(1,...series.flatMap(s=>s.values));const yTicks=4;const yStep=Math.ceil(maxY/yTicks)||1;const yMax=yStep*yTicks;const xStep=dates.length>1?plotW/(dates.length-1):0;const hidden=window._chartHidden||{};const visible=series.filter(s=>!hidden[s.key]);let svg='<svg class="chart-canvas" viewBox="0 0 '+W+' '+H+'" preserveAspectRatio="xMidYMid meet">';svg+='<line x1="'+pad.l+'" y1="'+(pad.t+plotH)+'" x2="'+(pad.l+plotW)+'" y2="'+(pad.t+plotH)+'" stroke="#334155"/>';for(let i=0;i<=yTicks;i++){const y=pad.t+plotH-(plotH*i/yTicks);const val=yStep*i;svg+='<line x1="'+pad.l+'" y1="'+y+'" x2="'+(pad.l+plotW)+'" y2="'+y+'" stroke="#1e293b"/>';svg+='<text x="'+(pad.l-8)+'" y="'+(y+4)+'" fill="#64748b" font-size="11" text-anchor="end">'+val+'</text>'}dates.forEach((d,i)=>{const x=pad.l+(dates.length>1?i*xStep:plotW/2);if(i===0||i===dates.length-1||dates.length<=7){svg+='<text x="'+x+'" y="'+(H-8)+'" fill="#64748b" font-size="11" text-anchor="middle">'+fmtChartDate(d)+'</text>'}});visible.forEach(s=>{const pts=s.values.map((v,i)=>{const x=pad.l+(dates.length>1?i*xStep:plotW/2);const y=pad.t+plotH-(v/yMax)*plotH;return x+','+y}).join(' ');svg+='<polyline fill="none" stroke="'+s.color+'" stroke-width="2" stroke-linejoin="round" stroke-linecap="round" points="'+pts+'"/>';s.values.forEach((v,i)=>{if(!v)return;const x=pad.l+(dates.length>1?i*xStep:plotW/2);const y=pad.t+plotH-(v/yMax)*plotH;svg+='<circle cx="'+x+'" cy="'+y+'" r="3" fill="'+s.color+'"/>'})});svg+='</svg>';host.innerHTML=svg;legend.innerHTML=series.map(s=>'<span class="chart-legend-item'+(hidden[s.key]?' off':'')+'" data-key="'+esc(s.key)+'" data-action="toggleChartSeries"><span class="chart-legend-swatch" style="background:'+s.color+'"></span>'+esc(s.label)+'</span>').join('')}
function toggleChartSeries(key){window._chartHidden=window._chartHidden||{};window._chartHidden[key]=!window._chartHidden[key];if(window._lastTrend)drawRequestTrendChart(window._lastTrend)}
async function loadRateLimitStats(){const [reqData,rlData]=await Promise.all([api('/request-stats'),api('/rate-limit-stats')]);const rs=reqData.stats;window._lastTrend=rs.trend;drawRequestTrendChart(rs.trend);const cat=rs.byCategory;document.getElementById('requestStatsGrid').innerHTML=[
  ['总请求',rs.totalRequests],['2xx 成功',cat.success2xx],['4xx 客户端',cat.client4xx],['5xx 服务端',cat.server5xx],['其他',cat.other]
].map(([l,v])=>'<div class="stat"><div class="label">'+l+'</div><div class="value">'+v+'</div></div>').join('');
const scB=document.getElementById('statusCodeBody');if(!rs.byStatusCode.length){scB.innerHTML='<tr><td colspan="3" class="empty">暂无</td></tr>'}else{const total=rs.totalRequests||1;scB.innerHTML=rs.byStatusCode.map(r=>'<tr><td><span class="badge '+statusCodeBadge(r.statusCode)+'">'+r.statusCode+'</span></td><td>'+r.count+'</td><td>'+(100*r.count/total).toFixed(1)+'%</td></tr>').join('')}
const pB=document.getElementById('topPathsBody');if(!rs.topPaths.length){pB.innerHTML='<tr><td colspan="2" class="empty">暂无</td></tr>'}else{pB.innerHTML=rs.topPaths.map(r=>'<tr><td><code>'+esc(r.pathGroup)+'</code></td><td>'+r.count+'</td></tr>').join('')}
const s=rlData.stats;document.getElementById('rateLimitStatsGrid').innerHTML='<div class="stat"><div class="label">今日 429 次数</div><div class="value">'+s.todayCount+'</div></div>';
const ipB=document.getElementById('topIpsBody');if(!s.topIps.length){ipB.innerHTML='<tr><td colspan="2" class="empty">暂无</td></tr>'}else{ipB.innerHTML=s.topIps.map(r=>'<tr><td><code>'+esc(r.ip)+'</code></td><td>'+r.count+'</td></tr>').join('')}
const uB=document.getElementById('topUsersBody');if(!s.topUsers.length){uB.innerHTML='<tr><td colspan="2" class="empty">暂无</td></tr>'}else{uB.innerHTML=s.topUsers.map(r=>'<tr><td>'+esc(r.username)+' (#'+r.userId+')</td><td>'+r.count+'</td></tr>').join('')}}
async function loadRegistration(){const d=await api('/registration');document.getElementById('regEnabled').checked=!!(d.registration&&d.registration.enabled)}
async function saveRegistration(){await api('/registration',{method:'PUT',body:JSON.stringify({enabled:document.getElementById('regEnabled').checked})});alert('注册设置已保存')}
async function loadMaintenance(){const d=await api('/maintenance');const m=d.maintenance;const t=d.turnstile||{};document.getElementById('turnstileEnabled').checked=!!t.enabled;document.getElementById('turnstileSiteKey').value=t.siteKey||'';document.getElementById('turnstileSecretKey').value='';const hint=document.getElementById('turnstileSecretHint');if(t.hasSecret){hint.textContent='已保存 Secret Key（留空表示不修改）';hint.style.color='#86efac'}else{hint.textContent='尚未配置 Secret Key';hint.style.color='#94a3b8'}document.getElementById('maintEnabled').checked=!!m.enabled;document.getElementById('maintMessage').value=m.message||'';document.getElementById('maintBlockLease').checked=!!m.blockLease;document.getElementById('maintBlockSend').checked=!!m.blockSend;document.getElementById('maintBlockMailbox').checked=!!m.blockMailboxCreate;updateMaintenancePreview()}
function readMaintenanceForm(){return{enabled:document.getElementById('maintEnabled').checked,message:document.getElementById('maintMessage').value,blockLease:document.getElementById('maintBlockLease').checked,blockSend:document.getElementById('maintBlockSend').checked,blockMailboxCreate:document.getElementById('maintBlockMailbox').checked,turnstile:{enabled:document.getElementById('turnstileEnabled').checked,siteKey:document.getElementById('turnstileSiteKey').value.trim(),secretKey:document.getElementById('turnstileSecretKey').value}}}
function getMaintenanceBlockedLabelsClient(m){const labels=[];if(m.blockSend)labels.push('发送邮件');if(m.blockMailboxCreate)labels.push('创建新邮箱（含 API 租用）');else if(m.blockLease)labels.push('API 租用随机邮箱');return labels}
function buildMaintenanceDisplayMessageClient(m){if(!m.enabled)return'';const custom=(m.message||'').trim();const blocked=getMaintenanceBlockedLabelsClient(m);if(!blocked.length)return custom||'系统维护中，请稍后再试';const blockedText='暂停服务：'+blocked.join('、')+'。';return custom?custom+' '+blockedText:'系统维护中。'+blockedText}
function updateMaintenancePreview(){const m=readMaintenanceForm();const el=document.getElementById('maintPreview');if(!m.enabled){el.style.display='none';return}el.style.display='block';el.innerHTML='<strong>用户端将看到：</strong><br>'+esc(buildMaintenanceDisplayMessageClient(m))}
async function saveMaintenance(){const body=readMaintenanceForm();await api('/maintenance',{method:'PUT',body:JSON.stringify(body)});alert('已保存');updateMaintenancePreview()}
function dateToUnixStart(d){if(!d)return undefined;const t=new Date(d+'T00:00:00');return Math.floor(t.getTime()/1000)}
function dateToUnixEnd(d){if(!d)return undefined;const t=new Date(d+'T23:59:59');return Math.floor(t.getTime()/1000)}
async function loadAuditLogs(page){window._auditPage=page;const from=dateToUnixStart(document.getElementById('auditFrom').value);const to=dateToUnixEnd(document.getElementById('auditTo').value);let q='?page='+page+'&limit=50';if(from)q+='&from='+from;if(to)q+='&to='+to;const d=await api('/audit-logs'+q);const b=document.getElementById('auditBody');if(!d.logs.length){b.innerHTML='<tr><td colspan="5" class="empty">暂无日志</td></tr>'}else{b.innerHTML=d.logs.map(l=>'<tr><td>'+fmtTime(l.createdAt)+'</td><td>'+esc(l.actorType)+(l.actorName?': '+esc(l.actorName):'')+'</td><td><code>'+esc(l.action)+'</code></td><td><code>'+esc(l.detail?JSON.stringify(l.detail):'-')+'</code></td><td>'+esc(l.ip||'-')+'</td></tr>').join('')}
const totalPages=Math.max(1,Math.ceil(d.total/d.limit));document.getElementById('auditPagination').innerHTML='<span>共 '+d.total+' 条 · 第 '+d.page+' / '+totalPages+' 页</span>'+(d.page>1?'<button class="btn btn-sm" data-action="loadAuditLogs" data-page="'+(d.page-1)+'">上一页</button>':'')+(d.page<totalPages?'<button class="btn btn-sm" data-action="loadAuditLogs" data-page="'+(d.page+1)+'">下一页</button>':'')}
const RATE_PLANS={free:{limit:60,burst:null},pro:{limit:600,burst:30},team:{limit:3000,burst:200}};
function fmtRateLimit(u){const l=u.rateLimitPerMin??60;const b=u.rateLimitBurst;return l+'/min'+(b?' (+'+b+' burst)':'');}
function detectRatePlan(u){const l=u.rateLimitPerMin??60;const b=u.rateLimitBurst??null;for(const[k,p]of Object.entries(RATE_PLANS)){if(p.limit===l&&p.burst===b)return k}return'custom'}
function applyRatePlan(){const p=document.getElementById('userRatePlan').value;if(p==='custom')return;const plan=RATE_PLANS[p];document.getElementById('userRateLimit').value=plan.limit;document.getElementById('userRateBurst').value=plan.burst??''}
async function loadUsers(){const d=await api('/users');const b=document.getElementById('usersBody');const fmtQ=q=>q<0?'无限':q;if(!d.users.length){b.innerHTML='<tr><td colspan="8" class="empty">暂无用户</td></tr>';return}b.innerHTML=d.users.map(u=>'<tr><td>'+u.id+'</td><td>'+esc(u.username)+'</td><td>'+esc(u.role)+'</td><td>'+fmtQ(u.dailySendQuota)+'</td><td>'+fmtQ(u.dailyLeaseQuota??300)+'</td><td>'+fmtRateLimit(u)+'</td><td><span class="badge '+(u.enabled?'badge-ok':'badge-off')+'">'+(u.enabled?'启用':'禁用')+'</span></td><td><button class="btn btn-sm" data-action="editUser" data-id="'+u.id+'">编辑</button> <button class="btn btn-danger btn-sm" data-action="deleteUser" data-id="'+u.id+'">删除</button></td></tr>').join('');window._users=d.users}
function showUserModal(){document.getElementById('userModalTitle').textContent='新增用户';document.getElementById('userId').value='';document.getElementById('userUsername').value='';document.getElementById('userPassword').value='';document.getElementById('userRole').value='user';document.getElementById('userQuota').value='50';document.getElementById('userLeaseQuota').value='300';document.getElementById('userRatePlan').value='free';applyRatePlan();document.getElementById('userMaxTokens').value='3';document.getElementById('userEnabledGroup').style.display='none';showModal('userModal')}
function editUser(id){const u=(window._users||[]).find(x=>x.id===id);if(!u)return;document.getElementById('userModalTitle').textContent='编辑用户';document.getElementById('userId').value=u.id;document.getElementById('userUsername').value=u.username;document.getElementById('userUsername').disabled=true;document.getElementById('userPassword').value='';document.getElementById('userRole').value=u.role;document.getElementById('userQuota').value=u.dailySendQuota;document.getElementById('userLeaseQuota').value=u.dailyLeaseQuota??300;document.getElementById('userRatePlan').value=detectRatePlan(u);document.getElementById('userRateLimit').value=u.rateLimitPerMin??60;document.getElementById('userRateBurst').value=u.rateLimitBurst??'';document.getElementById('userMaxTokens').value=u.maxUserTokens??3;document.getElementById('userEnabled').value=u.enabled?'1':'0';document.getElementById('userEnabledGroup').style.display='block';showModal('userModal')}
async function saveUser(){const id=document.getElementById('userId').value;const burstRaw=document.getElementById('userRateBurst').value;const body={username:document.getElementById('userUsername').value,password:document.getElementById('userPassword').value,role:document.getElementById('userRole').value,dailySendQuota:parseInt(document.getElementById('userQuota').value)||50,dailyLeaseQuota:parseInt(document.getElementById('userLeaseQuota').value)||300,rateLimitPerMin:parseInt(document.getElementById('userRateLimit').value)||60,rateLimitBurst:burstRaw===''?null:parseInt(burstRaw)||null,maxUserTokens:parseInt(document.getElementById('userMaxTokens').value,10)||3};if(id){body.enabled=document.getElementById('userEnabled').value==='1';if(!body.password)delete body.password;await api('/users/'+id,{method:'PUT',body:JSON.stringify(body)})}else{if(!body.username||!body.password){alert('用户名和密码必填');return}await api('/users',{method:'POST',body:JSON.stringify(body)})}document.getElementById('userUsername').disabled=false;hideModal('userModal');loadUsers()}
async function deleteUser(id){if(!confirm('确定删除此用户？'))return;await api('/users/'+id,{method:'DELETE'});loadUsers()}
async function loadAnnouncements(){const d=await api('/announcements');const b=document.getElementById('announcementsBody');if(!d.announcements.length){b.innerHTML='<tr><td colspan="6" class="empty">暂无公告</td></tr>';return}b.innerHTML=d.announcements.map(a=>'<tr><td>'+a.id+'</td><td>'+esc(a.title)+'</td><td>'+fmtTime(a.createdAt)+'</td><td><span class="badge '+(a.enabled?'badge-ok':'badge-off')+'">'+(a.enabled?'启用':'禁用')+'</span></td><td>'+(a.readCount??0)+'</td><td><button class="btn btn-sm" data-action="editAnnouncement" data-id="'+a.id+'">编辑</button> <button class="btn btn-danger btn-sm" data-action="deleteAnnouncement" data-id="'+a.id+'">删除</button></td></tr>').join('');window._announcements=d.announcements}
function showAnnouncementModal(){document.getElementById('announcementModalTitle').textContent='新增公告';document.getElementById('announcementId').value='';document.getElementById('announcementTitle').value='';document.getElementById('announcementContent').value='';document.getElementById('announcementEnabled').value='1';showModal('announcementModal')}
function editAnnouncement(id){const a=(window._announcements||[]).find(x=>x.id===id);if(!a)return;document.getElementById('announcementModalTitle').textContent='编辑公告';document.getElementById('announcementId').value=a.id;document.getElementById('announcementTitle').value=a.title;document.getElementById('announcementContent').value=a.content;document.getElementById('announcementEnabled').value=a.enabled?'1':'0';showModal('announcementModal')}
async function saveAnnouncement(){const id=document.getElementById('announcementId').value;const title=document.getElementById('announcementTitle').value.trim();const content=document.getElementById('announcementContent').value.trim();if(!title||!content){alert('标题和内容必填');return}const body={title,content,enabled:document.getElementById('announcementEnabled').value==='1'};if(id){await api('/announcements/'+id,{method:'PUT',body:JSON.stringify(body)})}else{await api('/announcements',{method:'POST',body:JSON.stringify(body)})}hideModal('announcementModal');loadAnnouncements()}
async function deleteAnnouncement(id){if(!confirm('确定删除此公告？'))return;await api('/announcements/'+id,{method:'DELETE'});loadAnnouncements()}
async function loadDomains(){const d=await api('/domains');window._domains=d.domains||[];window._brevoConfigured=!!d.brevoConfigured;const hint=document.getElementById('domainBrevoHint');if(d.brevoConfigured){hint.textContent='BREVO_API_KEY 已配置';hint.style.color='#86efac'}else{hint.textContent='⚠ 未配置 BREVO_API_KEY，无法添加新域名';hint.style.color='#fcd34d'}const b=document.getElementById('domainsBody');if(!window._domains.length){b.innerHTML='<tr><td colspan="7" class="empty">暂无域名，请从环境变量导入或手动添加</td></tr>';return}b.innerHTML=window._domains.map(dom=>'<tr><td>'+dom.id+'</td><td><code>'+esc(dom.domain)+'</code></td><td>'+(dom.isDefault?'<span class="badge badge-ok">默认</span>':'<button class="btn btn-sm" data-action="setDefaultDomain" data-id="'+dom.id+'">设为默认</button>')+'</td><td><span class="badge '+(dom.cloudflareReady?'badge-ok':'badge-warn')+'">'+(dom.cloudflareReady?'已确认':'未确认')+'</span></td><td><span class="badge '+(dom.brevoVerified?'badge-ok':'badge-warn')+'">'+(dom.brevoVerified?'已认证':'未认证')+'</span></td><td><span class="badge '+(dom.enabled?'badge-ok':'badge-off')+'">'+(dom.enabled?'启用':'禁用')+'</span></td><td>'+(!dom.cloudflareReady||!dom.brevoVerified?'<button class="btn btn-sm" data-action="confirmDomainReady" data-id="'+dom.id+'">确认已配置</button> ':'')+(dom.enabled?'<button class="btn btn-sm" data-action="toggleDomainEnabled" data-id="'+dom.id+'" data-enabled="false">禁用</button>':'<button class="btn btn-sm" data-action="toggleDomainEnabled" data-id="'+dom.id+'" data-enabled="true">启用</button>')+' <button class="btn btn-danger btn-sm" data-action="deleteDomain" data-id="'+dom.id+'">删除</button></td></tr>').join('')}
function showDomainModal(){if(!window._brevoConfigured){alert('请先在 Worker 环境变量中配置 BREVO_API_KEY');return}document.getElementById('domainName').value='';document.getElementById('domainCfReady').checked=false;document.getElementById('domainBrevoReady').checked=false;document.getElementById('domainSetDefault').checked=false;showModal('domainModal')}
async function saveDomain(){const domain=document.getElementById('domainName').value.trim();const cloudflareReady=document.getElementById('domainCfReady').checked;const brevoVerified=document.getElementById('domainBrevoReady').checked;const isDefault=document.getElementById('domainSetDefault').checked;if(!domain){alert('请填写域名');return}if(!cloudflareReady||!brevoVerified){alert('请先完成 Cloudflare 与 Brevo 配置，并勾选两项确认');return}const r=await api('/domains',{method:'POST',body:JSON.stringify({domain,cloudflareReady,brevoVerified,isDefault})});if(!r.success){alert(r.error||'添加失败');return}hideModal('domainModal');loadDomains()}
async function toggleDomainEnabled(id,enabled){const dom=(window._domains||[]).find(x=>x.id===id);if(enabled&&dom&&(!dom.cloudflareReady||!dom.brevoVerified)){alert('请先点击「确认已配置」，或删除后重新添加并勾选 Cloudflare / Brevo 确认项');return}const r=await api('/domains/'+id,{method:'PUT',body:JSON.stringify({enabled})});if(!r.success){alert(r.error||'更新失败');return}loadDomains()}
async function confirmDomainReady(id){const dom=(window._domains||[]).find(x=>x.id===id);if(!dom)return;if(!window._brevoConfigured){alert('请先在 Worker 环境变量中配置 BREVO_API_KEY');return}if(!confirm('确认域名 '+dom.domain+' 已在 Cloudflare 配置 Email Routing 指向 zMailR，且已在 Brevo 完成发信认证？'))return;const r=await api('/domains/'+id,{method:'PUT',body:JSON.stringify({cloudflareReady:true,brevoVerified:true})});if(!r.success){alert(r.error||'更新失败');return}loadDomains()}
async function setDefaultDomain(id){const r=await api('/domains/'+id,{method:'PUT',body:JSON.stringify({isDefault:true,enabled:true})});if(!r.success){alert(r.error||'设置失败');return}loadDomains()}
async function deleteDomain(id){const dom=(window._domains||[]).find(x=>x.id===id);if(!confirm('确定删除域名 '+(dom?dom.domain:id)+' ？'))return;const r=await api('/domains/'+id,{method:'DELETE'});if(!r.success){alert(r.error||'删除失败');return}loadDomains()}
async function loadRules(){const d=await api('/rules');const b=document.getElementById('rulesBody');const ub=document.getElementById('userRulesBody');if(!d.rules.length){b.innerHTML='<tr><td colspan="7" class="empty">暂无全局规则</td></tr>'}else{b.innerHTML=d.rules.map(r=>'<tr><td>'+r.id+'</td><td>'+esc(r.domain)+'</td><td><code>'+esc(r.regex)+'</code></td><td>'+r.priority+'</td><td><span class="badge '+(r.enabled?'badge-ok':'badge-off')+'">'+(r.enabled?'启用':'禁用')+'</span></td><td>'+esc(r.remark||'-')+'</td><td><button class="btn btn-sm" data-action="editRule" data-id="'+r.id+'">编辑</button> <button class="btn btn-danger btn-sm" data-action="deleteRule" data-id="'+r.id+'">删除</button></td></tr>').join('')};window._rules=d.rules;if(!d.userRules||!d.userRules.length){ub.innerHTML='<tr><td colspan="8" class="empty">暂无用户规则</td></tr>'}else{ub.innerHTML=d.userRules.map(r=>'<tr><td>'+r.id+'</td><td>'+esc(r.username)+'</td><td>'+esc(r.domain)+'</td><td><code>'+esc(r.regex)+'</code></td><td>'+r.priority+'</td><td><span class="badge '+(r.enabled?'badge-ok':'badge-off')+'">'+(r.enabled?'启用':'禁用')+'</span></td><td>'+esc(r.remark||'-')+'</td><td><button class="btn btn-danger btn-sm" data-action="deleteUserRule" data-id="'+r.id+'">删除</button></td></tr>').join('')}}
function showRuleModal(){document.getElementById('ruleModalTitle').textContent='新增规则';document.getElementById('ruleId').value='';document.getElementById('ruleDomain').value='*';document.getElementById('ruleRegex').value='';document.getElementById('rulePriority').value='0';document.getElementById('ruleRemark').value='';document.getElementById('ruleEnabled').value='1';showModal('ruleModal')}
function editRule(id){const r=(window._rules||[]).find(x=>x.id===id);if(!r)return;document.getElementById('ruleModalTitle').textContent='编辑规则';document.getElementById('ruleId').value=r.id;document.getElementById('ruleDomain').value=r.domain;document.getElementById('ruleRegex').value=r.regex;document.getElementById('rulePriority').value=r.priority;document.getElementById('ruleRemark').value=r.remark||'';document.getElementById('ruleEnabled').value=r.enabled?'1':'0';showModal('ruleModal')}
async function saveRule(){const id=document.getElementById('ruleId').value;const remark=document.getElementById('ruleRemark').value.trim();const body={domain:document.getElementById('ruleDomain').value,regex:document.getElementById('ruleRegex').value,priority:parseInt(document.getElementById('rulePriority').value)||0,enabled:document.getElementById('ruleEnabled').value==='1',remark:remark||null};if(id){await api('/rules/'+id,{method:'PUT',body:JSON.stringify(body)})}else{await api('/rules',{method:'POST',body:JSON.stringify(body)})}hideModal('ruleModal');loadRules()}
async function deleteRule(id){if(!confirm('确定删除此规则？'))return;await api('/rules/'+id,{method:'DELETE'});loadRules()}
async function deleteUserRule(id){if(!confirm('确定删除此用户规则？'))return;await api('/rules/user/'+id,{method:'DELETE'});loadRules()}
async function runExtractTest(){const fromAddress=document.getElementById('testRunFrom').value.trim();const subject=document.getElementById('testRunSubject').value;const text=document.getElementById('testRunText').value;const userIdRaw=document.getElementById('testRunUserId').value.trim();if(!fromAddress){alert('请填写发件人');return}const body={fromAddress,subject,text};if(userIdRaw)body.userId=parseInt(userIdRaw,10);const d=await api('/extract-rules/test-run',{method:'POST',body:JSON.stringify(body)});const summary=document.getElementById('testRunSummary');const b=document.getElementById('testRunBody');if(!d.rules.length){b.innerHTML='<tr><td colspan="8" class="empty">无适用规则</td></tr>'}else{b.innerHTML=d.rules.map(r=>'<tr'+(r.matched&&d.matchedRuleId===r.ruleId?' style="background:#14532d33"':'')+'><td>'+r.order+'</td><td>'+r.ruleId+'</td><td>'+esc(r.domain)+'</td><td>'+r.priority+'</td><td><code>'+esc(r.regex)+'</code></td><td><span class="badge '+(r.matched?'badge-ok':'badge-off')+'">'+(r.matched?'是':'否')+'</span></td><td>'+esc(r.extractedCode||'-')+'</td><td>'+esc(r.remark||'-')+'</td></tr>').join('')}if(d.extractedCode){summary.textContent='最终提取: '+d.extractedCode+(d.matchedRuleId?'（规则 #'+d.matchedRuleId+(d.matchedRuleDomain?' · '+d.matchedRuleDomain:'')+'）':'（内置兜底）')}else{summary.textContent='未提取到验证码'}}
(function(){try{var t=localStorage.getItem('theme');if(t==='light')document.documentElement.classList.add('light')}catch(e){}})();
function bindStaticEvents(){
  ['maintEnabled','maintBlockLease','maintBlockSend','maintBlockMailbox'].forEach(function(id){var el=document.getElementById(id);if(el)el.addEventListener('change',updateMaintenancePreview);});
  var msg=document.getElementById('maintMessage');if(msg)msg.addEventListener('input',updateMaintenancePreview);
  var rp=document.getElementById('userRatePlan');if(rp)rp.addEventListener('change',applyRatePlan);
}
function handleAction(el){
  var action=el.dataset.action;
  var id=el.dataset.id!==undefined?Number(el.dataset.id):undefined;
  switch(action){
    case 'doLogin':return doLogin();
    case 'doLogout':return doLogout();
    case 'loadHealthStatus':return loadHealthStatus();
    case 'saveRegistration':return saveRegistration();
    case 'showUserModal':return showUserModal();
    case 'showAnnouncementModal':return showAnnouncementModal();
    case 'setTemplateFilter':return setTemplateFilter(el.dataset.filter);
    case 'loadRuleTemplates':return loadRuleTemplates();
    case 'runExtractTest':return runExtractTest();
    case 'showRuleModal':return showRuleModal();
    case 'loadRateLimitStats':return loadRateLimitStats();
    case 'showDomainModal':return showDomainModal();
    case 'loadDomains':return loadDomains();
    case 'saveMaintenance':return saveMaintenance();
    case 'loadAuditLogs':return loadAuditLogs(Number(el.dataset.page||1));
    case 'hideModal':return hideModal(el.dataset.modal);
    case 'saveDomain':return saveDomain();
    case 'saveAnnouncement':return saveAnnouncement();
    case 'saveUser':return saveUser();
    case 'saveRule':return saveRule();
    case 'approveTemplate':return approveTemplate(id);
    case 'rejectTemplate':return rejectTemplate(id);
    case 'deleteTemplate':return deleteTemplate(id);
    case 'toggleChartSeries':return toggleChartSeries(el.dataset.key);
    case 'editUser':return editUser(id);
    case 'deleteUser':return deleteUser(id);
    case 'editAnnouncement':return editAnnouncement(id);
    case 'deleteAnnouncement':return deleteAnnouncement(id);
    case 'setDefaultDomain':return setDefaultDomain(id);
    case 'confirmDomainReady':return confirmDomainReady(id);
    case 'toggleDomainEnabled':return toggleDomainEnabled(id,el.dataset.enabled==='true');
    case 'deleteDomain':return deleteDomain(id);
    case 'editRule':return editRule(id);
    case 'deleteRule':return deleteRule(id);
    case 'deleteUserRule':return deleteUserRule(id);
  }
}
document.body.addEventListener('click',function(e){
  var tab=e.target.closest('.tab[data-tab]');
  if(tab){switchTab(tab.dataset.tab);return;}
  var el=e.target.closest('[data-action]');
  if(el)handleAction(el);
});
(async()=>{bindStaticEvents();await initAdminTurnstile();try{const d=await api('/stats');if(d.success){showApp();loadAll()}}catch{showLogin()}})();
document.getElementById('passwordInput').addEventListener('keydown',e=>{if(e.key==='Enter')doLogin()});
`;
}
